name: publish
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://registry.npmjs.org"
      - name: install
        run: yarn install
      - name: Can Publish
        run: yarn can-npm-publish --verbose
      - name: typecheck
        run: yarn run typecheck:ci
      - name: lint
        run: yarn run lint:ci
      - name: format
        run: yarn run format:ci
      - name: build
        run: yarn run build
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: doc
        run: npm run typedoc src
      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
