on:
  push:
    branches:
      - "main"
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install npm packages
        run: |
          yarn install
      - name: typecheck
        run: yarn run typecheck:ci
      - name: lint
        run: yarn run lint:ci
      - name: format
        run: yarn run format:ci
      - name: doc
        run: yarn run typedoc src
      - name: build
        run: yarn run build
      - name: Can Publish
        run: yarn can-npm-publish --verbose
