on:
  push:
    branches:
      - "main"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install npm packages
        run: |
          npm install
      - name: typecheck
        run: npm run typecheck:ci
      - name: lint
        run: npm run lint:ci
      - name: format
        run: npm run format:ci
      - name: doc
        run: npm run typedoc src
      - name: build
        run: npm run build
      - name: Can Publish
        run: npx can-npm-publish --verbose
