on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install npm packages
        run: |
          npm install
      - name: test
        run: |
          npm run test
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project=default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
